In [1]:
import numpy as np
import algo as algo
import data_synth as data

In [2]:
X = np.random.randint(0, 100, size = (6, 6))
print(X)

[[ 5 83 86 59 50  3]
 [85 71 87 88  5 68]
 [94 95 47 52 96 62]
 [36 76 21 47  0 91]
 [86 59  3 48 84 75]
 [20 70  1 50 22 39]]


In [3]:
print(X[:, 3])

[59 88 52 47 48 50]


In [4]:
print(any((X[:, 3] > 11) & (X[:, 3] < 88)))

True


In [5]:
x = np.asarray([0.1, 0.4, 0.2, 0.7])
y = np.asarray([0.2, 0.8, 0.2, 0.7])

algo.m_cost(x, y, 2)

initial refs:
ref: [0.1 0.4 0.2 0.7]
mref: [0.2 0.8 0.4 1.4]


(0.0, array([2., 1., 0., 3.]), array([1., 2., 2., 1.]))

In [6]:
n = 4
seq = data.Seq(n = n)

print(seq.tree)
print('tree:')
print(seq.tree.matrix_form())
print(seq.I)
print("p:")
print(seq.p)
print(f"m: {seq.m}")
print(seq.X)
print()
print()

print(seq.D)

---------
name: 0
	parent: root
	children: [1]
name: 1
	parent: 0
	children: [2]
name: 2
	parent: 1
	children: [3]
name: 3
	parent: 2
	children: []
---------
tree:
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 2. 1. 1.]
 [1. 2. 4. 1.]
 [1. 2. 4. 2.]]
p:
[0.438795   0.08779426 0.15427663 0.31913411]
m: [1 2 4 2]
[[0.438795   0.438795   0.438795   0.438795  ]
 [0.08779426 0.17558853 0.08779426 0.08779426]
 [0.15427663 0.30855325 0.6171065  0.15427663]
 [0.31913411 0.63826821 1.27653643 0.63826821]]


[0.         0.561205   1.4202322  0.31913411]


In [8]:
X = seq.X + np.random.normal(0, 1/100, (n, n))

print("real dist:")
print(seq.X)
print("data:")
print(X)
ref = X[:,0].flatten()
print("I:")
print(seq.I)
m = seq.m
print(f'master M: {m}')

paths = np.zeros((n, n))
paths[:, 0] = np.arange(n)

for i in range(1, n):
    print(f"working on region {i} (", end = "")
    err, match, num = algo.m_cost(ref, X[:, i].flatten(), m[i], debug = True)
    print(f'FINAL ERROR FOR ROW: {err}')
    print(f'\tMATCHING: {match}')
    print(f'\tNUM: {num}, ACTUAL: {seq.I[:, i].flatten()}')

real dist:
[[0.438795   0.438795   0.438795   0.438795  ]
 [0.08779426 0.17558853 0.08779426 0.08779426]
 [0.15427663 0.30855325 0.6171065  0.15427663]
 [0.31913411 0.63826821 1.27653643 0.63826821]]
data:
[[0.436598   0.43957686 0.44938361 0.4352309 ]
 [0.09468279 0.16223514 0.07644116 0.07226567]
 [0.15606552 0.31673872 0.62138908 0.15088934]
 [0.33339033 0.63934698 1.28802832 0.6352748 ]]
I:
[[1. 1. 1. 1.]
 [1. 2. 1. 1.]
 [1. 2. 4. 1.]
 [1. 2. 4. 2.]]
master M: [1 2 4 2]
working on region 1 (data col: [0.43957686 0.16223514 0.31673872 0.63934698])
initial refs:
ref: [0.436598   0.09468279 0.15606552 0.33339033]
mref: [0.87319599 0.18936557 0.31213105 0.66678067]
j = 7, grabbing value 0.6667806658359594 for 0.639346982968875
updated refs:
	ref: [ 4.36597997e-01  9.46827859e-02  1.56065524e-01 -1.00000000e+02], 
	mref:[   0.87319599    0.18936557    0.31213105 -100.        ]
error: 0.027433682867084364, i: 3, j: 7
matches: [0. 0. 0. 3.]
numbers: [0. 0. 0. 2.]
j = 0, grabbing value 0.4